### PR TITLE
Update MIT license and copyright to CMakePCHCompiler Authors

### PR DESCRIPTION
**Pull request by nanoant**
@gjasny As requested by @mick-p1982 I am preparing update listing all authors in copyright. Let me know if this looks good for you.

### CODE REVIEW

**Comment by mick-p1982** [comment]
I can be Mick Pearson (https://github.com/mick-p1982) if you need a link/address. Even though my contribution is relatively minor, I may put this project in my profile to raise its visibility. Plus it's neat to have contributed to something so widely applicable/beneficial in a not insignificant way. Even if necessity made me do it :)

**Comment by nanoant** [comment]
@mick-p1982 I have replaced all attributions to my name with *"MakePCHCompiler Authors"* pointing to Contributor list where your name is at 2nd place. Hope it works for you.

**Comment by mick-p1982** [comment]
@nanoant Since you asked, I think a nice (more personable) touch would be to write first/last names out in a central document included with the files. Just as your name was in the original boiler-plate (which I like, not being a fan of multi-line preambles in sources files.)

IN-SHORT: Define "Authors" in a portable/future-proof way.

**Comment by nanoant** [comment]
@mick-p1982 I was exactly looking for some future-proof way, but I have found no way to have automated (auto-updating) list of contributors (aka "Authors") in README.md.

Of course I could put the names there by hand, but that's not future-proof, hence perfect way would be to simply have it automated. So far most close is a solution from [opencollective.com](https://opencollective.com) -- but this requires registering the project on their website, whereas the most popular automatic badge system [shields.io](https://shields.io) provides only contributor count badge.

Therefore I have used term "Authors" as copyright holders, linking to in the README to GitHub contributor list page -- as seen in other projects licenses, e.g. [Gogs](https://github.com/gogs/gogs/blob/master/LICENSE), [jquery](https://github.com/jquery/jquery/blob/master/LICENSE.txt) or [Julia](https://github.com/JuliaLang/julia/blob/master/LICENSE.md).

**Comment by mick-p1982** [comment]
@nanoant  Well, by "future-proof" I mean that when the files are copied, they are on disk, and that means they are future-proof... whereas if that link goes dead... they are not future-proof. 

I think a link is fine for small contributions, but hand edits is not hard. If you're willing to make my PR  into such a to-do (about nothing) then I think you write a few names down :)

Simply copying every Tom Dick & Harry's name down is not as personable as a hand written list. The fact that not all names are in the list, makes it more endearing. Since not all contributions are equal. Some require effort... some can be just fixing a typo. To include them all, automatically, would be a little bit insulting anyway.

**Pull request merged**
